CREATE TABLE VACCINE(
    IDNUM INTEGER(4),
    NAME VARCHAR(15) NOT NULL UNIQUE,
    TYPE VARCHAR(10),
    DOSE VARCHAR(10),
    DATE_OF_VACCINE DATE,
    AGE INTEGER(2),
    CHECK TYPE IN ('COVISHIELD','COVAXIN'),
    CHECK DOSE IN ('I','II''BOOSTER'),
    CHECK AGE > 14
);

SELECT * FROM VACCINE;

SELECT IDNUM,NAME,AGE FROM VACCINE;

SELECT * FROM VACCINE
    WHERE DOSE != 'BOOSTER';

SELECT NAME,DATE_OF_VACCCINE FROM VACCINE
    WHERE AGE BETWEEN 30 AND 45;

SELECT IDNUM,NAME FROM VACCINE
    WHERE DATE_OF_VACCINE BETWEEN '2021-01-01' AND '2022-01-01';

ALTER TABLE VACCINE
ADD COMORBIDITY VARCHAR(15);

